server:
  port: 16666
eureka:
  instance:
    hostname: eureka16666.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka16667.com:16667/eureka/,http://eureka16668.com:16668/eureka/